name: zig-code

on:
  push:
    branches:
      - "main"
      - "master"
  pull_request:
    branches:
      - "main"
      - "master"

jobs:
  clang-format:
    name: Check if zig code compiles and runs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup zig
        uses: mlugg/setup-zig@v2

      - name: Setup just
        uses: extractions/setup-just@v3

      - name: Compile and run zig code
        run: just z-run
